CM-105: fetch when default filters change
openimis/openimis-fe-core_js pull request #125
Opened 2023-06-14 13:27 UTC by jdolkowski

https://openimis.atlassian.net/browse/CM-105

When using cache default filters were not fetched once changed. Changing default filters fill result in filtering.

2023-06-14 15:05 UTC, sniedzielski requested changes
I requested change because I'm afraid that this solution could break custom filters implementation provided in CM-71. We have to think how to integrate our features to have both working as expected.

2023-06-14 15:11 UTC, sniedzielski commented on src/components/generics/Searcher.js
> +  componentDidUpdate(prevProps, prevState, snapshot) {
![Peek 2023-06-14 17-02](https://github.com/openimis/openimis-fe-core_js/assets/52816247/0253b4ee-78ea-4455-8099-076e8b92625b)
@jdolkowski This is how it works CM-71 after integrating with this change from core and social protection CM-71 with  CM-105

2023-06-15 12:15 UTC, jdolkowski commented on src/components/generics/Searcher.js
> +  componentDidUpdate(prevProps, prevState, snapshot) {
now it should work fine, it also caches filters for each tab

2023-06-15 13:01 UTC, sniedzielski commented on src/components/generics/Searcher.js
> +  componentDidUpdate(prevProps, prevState, snapshot) {
thx

2023-06-15 13:02 UTC, merged