ONI-121: Basic switcher of date formats.
openimis/openimis-fe-core_js pull request #131
Opened 2023-06-22 20:43 UTC by wzglinieckisoldevelo

Ticket: 
https://openimis.atlassian.net/browse/ONI-121

Changes:
- Added calendar type toggle to the navbar
- Changed behaviour of second calendar setting

2023-06-30 08:28 UTC, olewandowski1 commented on src/pickers/DatePicker.js
> +      withHistory(connect(mapStateToProps, {})(withTheme(withStyles(styles)(DatePicker)))),
Consider using _null_ instead of empty object. It will clearly communicate that the component does not dispatch any actions to the Redux store.

2023-06-30 08:32 UTC, olewandowski1 commented on src/components/RequireAuth.js
> +  const [isSecondaryCalendar, setSecondaryCalendar] = useBoolean(defaultValue);
There is no need to declare seperate const for default value, just remove _defaultValue_ and do like this:
`const [isSecondaryCalendar, setSecondaryCalendar] = useBoolean(false);`

2023-06-30 08:35 UTC, olewandowski1 commented on src/components/RequireAuth.js
> +  useEffect(() => {dispatch(toggleCurrentCalendarType(!isSecondaryCalendar))}, [isSecondaryCalendar])
You can remove curly brackets here:
`useEffect(() => dispatch(toggleCurrentCalendarType(!isSecondaryCalendar)), [isSecondaryCalendar]);`

2023-06-30 08:39 UTC, olewandowski1 commented on src/pickers/DatePicker.js
> +    if (this.props.isSecondaryCalendarEnabled){
Destructure _isSecondaryCalendarEnabled_ from props and then use it in if statement:
```
    const {
      intl,
      classes,
      disablePast,
      module,
      label,
      readOnly = false,
      required = false,
      fullWidth = true,
      format = "DD-MM-YYYY",
      reset,
      **isSecondaryCalendarEnabled**,
      ...otherProps
    } = this.props;

if (**isSecondaryCalendarEnabled**) {...}
```

2023-06-30 08:41 UTC, olewandowski1 commented on src/pickers/DatePicker.js
> +
Redundant line.

2023-06-30 08:41 UTC, olewandowski1 commented on src/index.js
> +
Redundant line.

2023-06-30 08:42 UTC, olewandowski1 commented on src/components/RequireAuth.js
> +import {Switch } from "@material-ui/core";
Add white space in front of Switch.

2023-06-30 08:43 UTC, olewandowski1 commented on src/components/RequireAuth.js
> +import {toggleCurrentCalendarType} from "../actions"
Add white spaces.

2023-06-30 08:50 UTC, olewandowski1 requested changes
@wzglinieckisoldevelo I left you some comments.

2023-07-11 13:50 UTC, olewandowski1 approved these changes
@wzglinieckisoldevelo LGTM

2023-07-12 08:08 UTC, delcroip approved these changes

2023-07-12 08:08 UTC, merged