OM-66: move mPass redirect to the utils
openimis/openimis-fe-core_js pull request #171
Opened 2023-11-03 11:44 UTC by jdolkowski

https://openimis.atlassian.net/browse/OM-66

2023-11-03 11:50 UTC, olewandowski1 commented on src/helpers/utils.js
> +import {M_PASS_LOGOUT_PATH} from "../constants";
Add extra space here

2023-11-03 13:53 UTC, olewandowski1 requested changes
@jdolkowski I left 1 comment.

2023-11-03 15:05 UTC, jdolkowski commented on src/helpers/utils.js
> +import {M_PASS_LOGOUT_PATH} from "../constants";
done

2023-11-06 07:33 UTC, olewandowski1 approved these changes
LGTM @jdolkowski

2023-11-06 08:44 UTC, merged